-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(PRICE*SALES_AMOUNT) from PRODUCT inner join OFFLINE_SALE on PRODUCT.PRODUCT_ID=OFFLINE_SALE.PRODUCT_ID group by PRODUCT_CODE ORDER BY SUM(PRICE*SALES_AMOUNT) DESC, PRODUCT_CODE ASC

# SELECT PRODUCT_CODE, PRICE, SALES_AMOUNT,SALES_DATE from PRODUCT inner join OFFLINE_SALE on PRODUCT.PRODUCT_ID=OFFLINE_SALE.PRODUCT_ID