-- 코드를 작성해주세요
SELECT (
    CASE
    WHEN DATE_FORMAT(DIFFERENTIATION_DATE,'%m')<=3
    THEN '1Q'
    WHEN DATE_FORMAT(DIFFERENTIATION_DATE,'%m')<=6
    THEN '2Q'
    WHEN DATE_FORMAT(DIFFERENTIATION_DATE,'%m')<=9
    THEN '3Q'
    ELSE '4Q'
    END
) AS QUARTER,COUNT(ID) AS ECOLI_COUNT FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER ASC