-- 코드를 입력하세요
SELECT P.PRODUCT_ID AS PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES FROM FOOD_PRODUCT P
INNER JOIN FOOD_ORDER O
ON O.PRODUCT_ID=P.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m')='2022-05'
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC