-- 코드를 입력하세요
SELECT USER_ID,NICKNAME, SUM(PRICE) as TOTAL_SALES from USED_GOODS_BOARD B
inner join USED_GOODS_USER U on B.WRITER_ID=U.USER_ID
where STATUS='DONE'
group by USER_ID
having TOTAL_SALES>=700000
order by TOTAL_SALES asc