-- 코드를 입력하세요
SELECT CAST(DATE_FORMAT(DATETIME,'%H') AS UNSIGNED) AS HOUR, COUNT(ANIMAL_ID) AS COUNT FROM ANIMAL_OUTS
WHERE DATE_FORMAT(DATETIME,'%H')>=9 AND DATE_FORMAT(DATETIME,'%H')<=19
GROUP BY HOUR
ORDER BY HOUR