-- 코드를 작성해주세요
SELECT I.ITEM_ID AS ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO I
INNER JOIN ITEM_TREE T ON I.ITEM_ID=T.ITEM_ID
WHERE PARENT_ITEM_ID IN (
    SELECT ITEM_ID FROM ITEM_INFO I
    WHERE RARITY='RARE'
)
ORDER BY ITEM_ID DESC


# SELECT IT.ITEM_ID, II.ITEM_NAME, II.RARITY FROM ITEM_INFO AS II
# INNER JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.ITEM_ID
# WHERE IT.PARENT_ITEM_ID IN
# (SELECT ITEM_ID
# FROM ITEM_INFO
# WHERE RARITY = "RARE")
# ORDER BY IT.ITEM_ID DESC