-- 코드를 작성해주세요
SELECT E.ID AS ID, E.GENOTYPE, S.GENOTYPE AS PARENT_GENOTYPE FROM ECOLI_DATA E
INNER JOIN ECOLI_DATA S ON S.ID=E.PARENT_ID
WHERE E.PARENT_ID IS NOT NULL AND E.GENOTYPE & S.GENOTYPE = S.GENOTYPE
ORDER BY ID ASC

# SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE FROM ECOLI_DATA A, ECOLI_DATA B
# WHERE A.PARENT_ID = B.ID
# AND B.GENOTYPE & A.GENOTYPE = B.GENOTYPE
# ORDER BY ID