-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH FROM FISH_INFO F
INNER JOIN FISH_NAME_INFO I ON F.FISH_TYPE=I.FISH_TYPE
WHERE (F.FISH_TYPE, LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY ID