-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) as TOTAL_ORDER from ICECREAM_INFO
inner join FIRST_HALF on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
group by ICECREAM_INFO.INGREDIENT_TYPE
order by TOTAL_ORDER asc