-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) as TOTAL_SALES from BOOK B
inner join BOOK_SALES S on B.BOOK_ID=S.BOOK_ID
where DATE_FORMAT(SALES_DATE,'%M')='January' AND DATE_FORMAT(SALES_DATE,'%Y')='2022'
group by CATEGORY
order by CATEGORY asc